import {
  AxiomSnapshot,
  Shopper,
  Product,
  ShopperEvent,
  MarketEvent,
  Opportunity,
  RecoveryAction,
  WebhookDelivery,
  Campaign,
} from "@/types/axiom";

const API_BASE = process.env.NEXT_PUBLIC_API_URL || "";

export const INITIAL_SNAPSHOT: AxiomSnapshot = {
  stats: {
    live_shoppers: 64,
    high_intent_shoppers: 28,
    revenue_at_risk: 194680,
    recovery_opportunities: 6,
    actions_triggered: 18,
    recovered_revenue: 216984,
    active_market_events: 6,
    total_events: 1624,
    conversion_rate: 42.8,
    avg_intent_score: 0.74,
    hesitation_loops_active: 14,
    webhooks_Dispatched: 24,
  },
  events: [
    {
      id: "evt_07",
      shopper_id: "shopper_4821",
      shopper_display_id: "#4821",
      event_type: "hesitation_detected",
      label: "AXIOM DETECTED HESITATION LOOP",
      detail: "91% Purchase Intent · 78% Drop-Off Risk · Price sensitivity confirmed",
      timestamp: new Date(Date.now() - 8000).toISOString(),
      product_id: "prod_black_denim",
      product_name: "Black Denim",
      product_price: 3899,
      is_axiom_signal: true,
    },
    {
      id: "evt_06",
      shopper_id: "shopper_4821",
      shopper_display_id: "#4821",
      event_type: "return_visit",
      label: "RETURNED",
      detail: "#4821 returned to Black Denim session",
      timestamp: new Date(Date.now() - 18000).toISOString(),
      product_id: "prod_black_denim",
      product_name: "Black Denim",
      product_price: 3899,
    },
    {
      id: "evt_05",
      shopper_id: "shopper_4821",
      shopper_display_id: "#4821",
      event_type: "cart_abandon",
      label: "LEFT CART",
      detail: "#4821 left cart without completing checkout",
      timestamp: new Date(Date.now() - 62000).toISOString(),
      product_id: "prod_black_denim",
      product_name: "Black Denim",
      product_price: 4398,
    },
    {
      id: "evt_04",
      shopper_id: "shopper_4821",
      shopper_display_id: "#4821",
      event_type: "price_check",
      label: "PRICE CHECK",
      detail: "#4821 checked price on Black Denim (3× check)",
      timestamp: new Date(Date.now() - 105000).toISOString(),
      product_id: "prod_black_denim",
      product_name: "Black Denim",
      product_price: 4398,
    },
    {
      id: "evt_03",
      shopper_id: "shopper_4821",
      shopper_display_id: "#4821",
      event_type: "add_to_cart",
      label: "ADDED TO CART",
      detail: "#4821 added Black Denim to cart · ₹4,398",
      timestamp: new Date(Date.now() - 180000).toISOString(),
      product_id: "prod_black_denim",
      product_name: "Black Denim",
      product_price: 4398,
    },
    {
      id: "evt_02",
      shopper_id: "shopper_4821",
      shopper_display_id: "#4821",
      event_type: "product_view",
      label: "PRODUCT VIEW",
      detail: "#4821 viewed Black Denim / ₹4,398",
      timestamp: new Date(Date.now() - 213000).toISOString(),
      product_id: "prod_black_denim",
      product_name: "Black Denim",
      product_price: 4398,
    },
    {
      id: "evt_01",
      shopper_id: "shopper_4821",
      shopper_display_id: "#4821",
      event_type: "search",
      label: "SEARCH",
      detail: '#4821 searched "black jeans"',
      timestamp: new Date(Date.now() - 236000).toISOString(),
      product_id: "prod_black_denim",
      product_name: "Black Denim",
      product_price: 4398,
      search_query: "black jeans",
    },
  ],
  shoppers: [
    {
      id: "shopper_4821",
      display_id: "#4821",
      name: "Aarav Mehta",
      email: "aarav.mehta@gmail.com",
      location: "Mumbai, IN",
      device: "iOS · Safari",
      sessions: 4,
      session_duration_sec: 845,
      total_events: 19,
      cart_items: ["prod_black_denim"],
      wishlist_items: ["prod_black_denim", "prod_wool_overcoat"],
      purchase_history: ["prod_ceramic_mug"],
      primary_product_id: "prod_black_denim",
      primary_product_name: "Black Denim",
      intent_score: 0.91,
      risk_score: 0.78,
      confidence: 0.94,
      hesitation_loop: true,
      predicted_next_action:
        "High probability of checkout completion within 12m following price-drop nudge (₹4,398 → ₹3,899)",
      signal_breakdown: {
        "Repeated product views": 18,
        "Added to cart": 27,
        "Price checks": 21,
        "Returned session": 14,
        "Checkout hesitation": 11,
      },
      behavioral_features: {
        search_frequency: 3,
        product_revisit_frequency: 4,
        session_duration_sec: 845,
        cart_additions: 2,
        cart_removals: 0,
        wishlist_activity: 2,
        price_check_frequency: 3,
        checkout_progression: 0.75,
        return_sessions: 3,
        product_affinity: 0.94,
        recency_score: 0.98,
        historical_conversion_rate: 0.33,
      },
      last_seen: new Date().toISOString(),
      first_seen: new Date(Date.now() - 5 * 86400000).toISOString(),
      status: "active",
    },
    {
      id: "shopper_2204",
      display_id: "#2204",
      name: "Ananya Nair",
      email: "ananya.nair@gmail.com",
      location: "Hyderabad, IN",
      device: "iOS · Safari",
      sessions: 6,
      session_duration_sec: 930,
      total_events: 22,
      cart_items: ["prod_studio_headphones"],
      wishlist_items: ["prod_studio_headphones", "prod_mech_keyboard"],
      purchase_history: ["prod_mech_keyboard"],
      primary_product_id: "prod_studio_headphones",
      primary_product_name: "Studio Monitor Headphones",
      intent_score: 0.89,
      risk_score: 0.74,
      confidence: 0.95,
      hesitation_loop: true,
      predicted_next_action:
        "Comparing acoustic specs & checking price history — dispatch 14.3% price-drop webhook",
      signal_breakdown: {
        "Added to cart": 26,
        "Product comparison": 20,
        "Price checks": 19,
        "Returned session": 14,
        "Checkout hesitation": 10,
      },
      behavioral_features: {
        search_frequency: 3,
        product_revisit_frequency: 6,
        session_duration_sec: 930,
        cart_additions: 2,
        cart_removals: 1,
        wishlist_activity: 2,
        price_check_frequency: 4,
        checkout_progression: 0.8,
        return_sessions: 5,
        product_affinity: 0.93,
        recency_score: 0.96,
        historical_conversion_rate: 0.5,
      },
      last_seen: new Date(Date.now() - 35000).toISOString(),
      first_seen: new Date(Date.now() - 9 * 86400000).toISOString(),
      status: "active",
    },
    {
      id: "shopper_3912",
      display_id: "#3912",
      name: "Priya Sharma",
      email: "priya.sharma@outlook.com",
      location: "Bengaluru, IN",
      device: "macOS · Arc",
      sessions: 5,
      session_duration_sec: 710,
      total_events: 16,
      cart_items: ["prod_skincare_serum", "prod_cosmetics_kit"],
      wishlist_items: ["prod_skincare_serum"],
      purchase_history: ["prod_cosmetics_kit"],
      primary_product_id: "prod_skincare_serum",
      primary_product_name: "Cellular Barrier Serum",
      intent_score: 0.88,
      risk_score: 0.69,
      confidence: 0.92,
      hesitation_loop: true,
      predicted_next_action:
        "Evaluating bundle threshold — responsive to price-drop alert on Cellular Barrier Serum",
      signal_breakdown: {
        "Added to cart": 25,
        "Repeated product views": 19,
        "Watchlist activity": 16,
        "Returned session": 15,
        "Price checks": 13,
      },
      behavioral_features: {
        search_frequency: 2,
        product_revisit_frequency: 5,
        session_duration_sec: 710,
        cart_additions: 2,
        cart_removals: 1,
        wishlist_activity: 3,
        price_check_frequency: 2,
        checkout_progression: 0.65,
        return_sessions: 4,
        product_affinity: 0.89,
        recency_score: 0.95,
        historical_conversion_rate: 0.4,
      },
      last_seen: new Date(Date.now() - 48000).toISOString(),
      first_seen: new Date(Date.now() - 11 * 86400000).toISOString(),
      status: "active",
    },
    {
      id: "shopper_6140",
      display_id: "#6140",
      name: "Vikram Singhania",
      email: "vikram.s@gmail.com",
      location: "Mumbai, IN",
      device: "macOS · Safari",
      sessions: 4,
      session_duration_sec: 780,
      total_events: 17,
      cart_items: ["prod_sneakers", "prod_black_denim"],
      wishlist_items: ["prod_sneakers"],
      purchase_history: ["prod_leather_crossbody"],
      primary_product_id: "prod_sneakers",
      primary_product_name: "Terra Runner Sneakers",
      intent_score: 0.86,
      risk_score: 0.71,
      confidence: 0.91,
      hesitation_loop: true,
      predicted_next_action:
        "High cart value (₹15,398) stalled at shipping step — send instant checkout recovery nudge",
      signal_breakdown: {
        "Added to cart": 25,
        "Checkout progression": 22,
        "Repeated product views": 16,
        "Price checks": 13,
        "Returned session": 10,
      },
      behavioral_features: {
        search_frequency: 2,
        product_revisit_frequency: 4,
        session_duration_sec: 780,
        cart_additions: 2,
        cart_removals: 0,
        wishlist_activity: 1,
        price_check_frequency: 3,
        checkout_progression: 0.85,
        return_sessions: 3,
        product_affinity: 0.88,
        recency_score: 0.94,
        historical_conversion_rate: 0.45,
      },
      last_seen: new Date(Date.now() - 90000).toISOString(),
      first_seen: new Date(Date.now() - 8 * 86400000).toISOString(),
      status: "active",
    },
    {
      id: "shopper_7719",
      display_id: "#7719",
      name: "Rohan Kapoor",
      email: "rohan.kapoor@gmail.com",
      location: "Delhi NCR, IN",
      device: "macOS · Chrome",
      sessions: 3,
      session_duration_sec: 620,
      total_events: 14,
      cart_items: ["prod_ceramic_mug"],
      wishlist_items: ["prod_ceramic_mug"],
      purchase_history: [],
      primary_product_id: "prod_ceramic_mug",
      primary_product_name: "Ceramic Mug Set",
      intent_score: 0.84,
      risk_score: 0.62,
      confidence: 0.89,
      hesitation_loop: false,
      predicted_next_action:
        "High sensitivity to stock depletion (12 units left) — trigger low-inventory urgency nudge",
      signal_breakdown: {
        "Added to cart": 24,
        "Inventory checks": 18,
        "Repeated product views": 17,
        "Search specificity": 13,
        "Watchlist activity": 12,
      },
      behavioral_features: {
        search_frequency: 4,
        product_revisit_frequency: 3,
        session_duration_sec: 620,
        cart_additions: 1,
        cart_removals: 0,
        wishlist_activity: 2,
        price_check_frequency: 2,
        checkout_progression: 0.5,
        return_sessions: 2,
        product_affinity: 0.86,
        recency_score: 0.92,
        historical_conversion_rate: 0.25,
      },
      last_seen: new Date(Date.now() - 120000).toISOString(),
      first_seen: new Date(Date.now() - 4 * 86400000).toISOString(),
      status: "active",
    },
    {
      id: "shopper_8093",
      display_id: "#8093",
      name: "Meera Iyer",
      email: "meera.iyer@gmail.com",
      location: "Chennai, IN",
      device: "iPadOS · Safari",
      sessions: 5,
      session_duration_sec: 1120,
      total_events: 21,
      cart_items: ["prod_coffee_table"],
      wishlist_items: ["prod_coffee_table", "prod_ceramic_mug"],
      purchase_history: ["prod_ceramic_mug"],
      primary_product_id: "prod_coffee_table",
      primary_product_name: "Nordic White Oak Coffee Table",
      intent_score: 0.82,
      risk_score: 0.66,
      confidence: 0.9,
      hesitation_loop: false,
      predicted_next_action:
        "High-ticket consideration (₹18,999) + only 7 units in stock — notify of 13.6% price drop",
      signal_breakdown: {
        "Time on product page": 23,
        "Added to cart": 22,
        "Repeated product views": 16,
        "Price checks": 12,
        "Returned session": 9,
      },
      behavioral_features: {
        search_frequency: 2,
        product_revisit_frequency: 5,
        session_duration_sec: 1120,
        cart_additions: 1,
        cart_removals: 0,
        wishlist_activity: 2,
        price_check_frequency: 3,
        checkout_progression: 0.6,
        return_sessions: 4,
        product_affinity: 0.91,
        recency_score: 0.9,
        historical_conversion_rate: 0.35,
      },
      last_seen: new Date(Date.now() - 180000).toISOString(),
      first_seen: new Date(Date.now() - 12 * 86400000).toISOString(),
      status: "active",
    },
  ],
  products: [
    {
      id: "prod_black_denim",
      name: "Black Denim",
      slug: "black-denim-slim-fit",
      category: "Denim & Apparel",
      price: 3899,
      original_price: 4398,
      competitor_price: 4199,
      currency: "INR",
      inventory: 38,
      brand: "Atelier Noir",
      description: "13.5oz Japanese selvedge black denim with raw matte hardware and tapered silhouette.",
      views: 1420,
      cart_adds: 61,
      wishlist_count: 184,
      purchases: 89,
      conversion_rate: 6.3,
      price_change_pct: -11.3,
      recovery_opportunity_level: "HIGH",
      interested_shoppers: 68,
      high_intent_shoppers: 23,
      intent_density: 0.89,
      price_history: [
        { price: 4398, date: "2026-09-20", event: "baseline" },
        { price: 4199, date: "2026-09-28", event: "adjustment" },
        { price: 3899, date: "2026-10-03", event: "price_drop" },
      ],
    },
    {
      id: "prod_ceramic_mug",
      name: "Ceramic Mug Set",
      slug: "ceramic-artisan-mug-set",
      category: "Home & Objects",
      price: 2499,
      original_price: 2499,
      competitor_price: 2750,
      currency: "INR",
      inventory: 12,
      brand: "Kinto Studio",
      description: "Hand-thrown stoneware mug set of 4 finished in warm ash reactive glaze.",
      views: 1890,
      cart_adds: 78,
      wishlist_count: 327,
      purchases: 134,
      conversion_rate: 7.1,
      price_change_pct: 0,
      recovery_opportunity_level: "HIGH",
      interested_shoppers: 94,
      high_intent_shoppers: 41,
      intent_density: 0.92,
      price_history: [
        { price: 2499, date: "2026-09-20", event: "baseline" },
        { price: 2499, date: "2026-10-03", event: "stable" },
      ],
    },
    {
      id: "prod_studio_headphones",
      name: "Studio Monitor Headphones",
      slug: "studio-monitor-headphones",
      category: "Electronics",
      price: 8999,
      original_price: 10499,
      competitor_price: 9499,
      currency: "INR",
      inventory: 29,
      brand: "Aether Audio",
      description: "Planar magnetic wireless studio headphones with adaptive acoustic isolation.",
      views: 1640,
      cart_adds: 52,
      wishlist_count: 264,
      purchases: 92,
      conversion_rate: 5.6,
      price_change_pct: -14.3,
      recovery_opportunity_level: "HIGH",
      interested_shoppers: 58,
      high_intent_shoppers: 18,
      intent_density: 0.86,
      price_history: [
        { price: 10499, date: "2026-09-20", event: "baseline" },
        { price: 8999, date: "2026-10-03", event: "price_drop" },
      ],
    },
    {
      id: "prod_sneakers",
      name: "Terra Runner Sneakers",
      slug: "terra-runner-sneakers",
      category: "Sneakers",
      price: 11499,
      original_price: 12995,
      competitor_price: 11999,
      currency: "INR",
      inventory: 21,
      brand: "Veloce Lab",
      description: "Carbon-plate everyday trainer in unbleached suede and Vibram micro-lug sole.",
      views: 2110,
      cart_adds: 74,
      wishlist_count: 310,
      purchases: 118,
      conversion_rate: 5.6,
      price_change_pct: -11.5,
      recovery_opportunity_level: "HIGH",
      interested_shoppers: 64,
      high_intent_shoppers: 19,
      intent_density: 0.84,
      price_history: [
        { price: 12995, date: "2026-09-20", event: "baseline" },
        { price: 11499, date: "2026-10-03", event: "price_drop" },
      ],
    },
    {
      id: "prod_skincare_serum",
      name: "Cellular Barrier Serum",
      slug: "cellular-barrier-serum",
      category: "Skincare",
      price: 1899,
      original_price: 2199,
      competitor_price: 1999,
      currency: "INR",
      inventory: 94,
      brand: "Derma Botanica",
      description: "20% stabilized L-ascorbic acid + ceramide complex for dermal barrier recovery.",
      views: 1350,
      cart_adds: 48,
      wishlist_count: 219,
      purchases: 112,
      conversion_rate: 8.3,
      price_change_pct: -13.6,
      recovery_opportunity_level: "HIGH",
      interested_shoppers: 52,
      high_intent_shoppers: 27,
      intent_density: 0.88,
      price_history: [
        { price: 2199, date: "2026-09-20", event: "baseline" },
        { price: 1899, date: "2026-10-03", event: "price_drop" },
      ],
    },
    {
      id: "prod_coffee_table",
      name: "Nordic White Oak Coffee Table",
      slug: "nordic-oak-coffee-table",
      category: "Furniture",
      price: 18999,
      original_price: 21999,
      competitor_price: 19999,
      currency: "INR",
      inventory: 7,
      brand: "Forma Living",
      description: "Solid kiln-dried white oak low table with architectural mortise joinery.",
      views: 980,
      cart_adds: 29,
      wishlist_count: 142,
      purchases: 41,
      conversion_rate: 4.2,
      price_change_pct: -13.6,
      recovery_opportunity_level: "HIGH",
      interested_shoppers: 39,
      high_intent_shoppers: 16,
      intent_density: 0.82,
      price_history: [
        { price: 21999, date: "2026-09-20", event: "baseline" },
        { price: 18999, date: "2026-10-03", event: "price_drop" },
      ],
    },
    {
      id: "prod_cosmetics_kit",
      name: "Velvet Matte Lip & Cheek Atelier",
      slug: "velvet-matte-cosmetics",
      category: "Cosmetics",
      price: 1649,
      original_price: 1899,
      competitor_price: 1799,
      currency: "INR",
      inventory: 64,
      brand: "Maison Lune",
      description: "Micro-pigment lip and cheek tint trio formulated with botanical squalane.",
      views: 1180,
      cart_adds: 44,
      wishlist_count: 195,
      purchases: 98,
      conversion_rate: 8.3,
      price_change_pct: -13.2,
      recovery_opportunity_level: "MEDIUM",
      interested_shoppers: 46,
      high_intent_shoppers: 15,
      intent_density: 0.76,
      price_history: [
        { price: 1899, date: "2026-09-20", event: "baseline" },
        { price: 1649, date: "2026-10-03", event: "price_drop" },
      ],
    },
    {
      id: "prod_mech_keyboard",
      name: "Machined Aluminum Field Keyboard",
      slug: "machined-field-keyboard",
      category: "Electronics",
      price: 6499,
      original_price: 7499,
      competitor_price: 6899,
      currency: "INR",
      inventory: 33,
      brand: "Tactile Works",
      description: "CNC 6063 aluminum 75% wireless mechanical keyboard with gasket mount.",
      views: 1240,
      cart_adds: 39,
      wishlist_count: 168,
      purchases: 73,
      conversion_rate: 5.9,
      price_change_pct: -13.3,
      recovery_opportunity_level: "MEDIUM",
      interested_shoppers: 42,
      high_intent_shoppers: 14,
      intent_density: 0.78,
      price_history: [
        { price: 7499, date: "2026-09-20", event: "baseline" },
        { price: 6499, date: "2026-10-03", event: "price_drop" },
      ],
    },
  ],
  opportunities: [
    {
      id: "opp_black_denim_price_drop",
      title: "HIGH INTENT + PRICE DROP",
      opportunity_type: "high_intent_price_drop",
      product_id: "prod_black_denim",
      product_name: "Black Denim",
      product_price: 3899,
      old_price: 4398,
      price_reduction: 499,
      inventory_remaining: 38,
      watchlist_count: 184,
      shopper_ids: ["shopper_4821", "shopper_6140"],
      shopper_count: 23,
      avg_intent: 0.91,
      avg_risk: 0.78,
      revenue_potential: 89677,
      trigger: "Price dropped 11.3% (₹4,398 → ₹3,899)",
      description:
        "23 shoppers with 91% average intent and repeated price checks have Black Denim in cart or watchlist following a ₹499 price reduction.",
      recommended_action: "Notify high-intent abandoned carts",
      action_channel: "In-app price-drop nudge + Webhook",
      urgency: "HIGH",
      status: "active",
      created_at: new Date(Date.now() - 120000).toISOString(),
    },
    {
      id: "opp_ceramic_mug_inventory",
      title: "INVENTORY PRESSURE",
      opportunity_type: "inventory_pressure",
      product_id: "prod_ceramic_mug",
      product_name: "Ceramic Mug Set",
      product_price: 2499,
      old_price: 2499,
      price_reduction: 0,
      inventory_remaining: 12,
      watchlist_count: 327,
      shopper_ids: ["shopper_7719", "shopper_8093"],
      shopper_count: 41,
      avg_intent: 0.84,
      avg_risk: 0.62,
      revenue_potential: 29988,
      trigger: "12 units remaining · 327 on watchlist · 41 high-intent",
      description:
        "Potential urgency opportunity: Ceramic Mug Set stock fell to 12 units while 41 high-intent shoppers actively revisit the product page.",
      recommended_action: "Dispatch low-stock scarcity signal to 41 high-intent shoppers",
      action_channel: "In-app urgency nudge + Push",
      urgency: "HIGH",
      status: "active",
      created_at: new Date(Date.now() - 360000).toISOString(),
    },
    {
      id: "opp_4821_hesitation_loop",
      title: "HESITATION LOOP INTERCEPTION",
      opportunity_type: "hesitation_loop",
      product_id: "prod_black_denim",
      product_name: "Black Denim",
      product_price: 3899,
      old_price: 4398,
      price_reduction: 499,
      inventory_remaining: 38,
      watchlist_count: 184,
      shopper_ids: ["shopper_4821"],
      shopper_count: 1,
      avg_intent: 0.91,
      avg_risk: 0.78,
      revenue_potential: 3899,
      trigger: "4× product views · added to cart · 3× price checks · returned session",
      description:
        "Shopper #4821 returned after abandoning cart and checking price 3 times. Immediate price-drop nudge unlocks checkout.",
      recommended_action: "Trigger instant in-app price-drop nudge",
      action_channel: "In-app nudge",
      urgency: "HIGH",
      status: "active",
      created_at: new Date(Date.now() - 60000).toISOString(),
    },
    {
      id: "opp_headphones_recovery",
      title: "HIGH INTENT + PRICE DROP",
      opportunity_type: "high_intent_price_drop",
      product_id: "prod_studio_headphones",
      product_name: "Studio Monitor Headphones",
      product_price: 8999,
      old_price: 10499,
      price_reduction: 1500,
      inventory_remaining: 29,
      watchlist_count: 264,
      shopper_ids: ["shopper_2204"],
      shopper_count: 18,
      avg_intent: 0.89,
      avg_risk: 0.74,
      revenue_potential: 161982,
      trigger: "Price dropped 14.3% (₹10,499 → ₹8,999)",
      description:
        "18 high-intent shoppers comparing Studio Monitor Headphones have active carts/watchlists after a ₹1,500 price drop.",
      recommended_action: "Activate price-drop recovery campaign",
      action_channel: "Webhook + Email Re-engagement",
      urgency: "HIGH",
      status: "active",
      created_at: new Date(Date.now() - 660000).toISOString(),
    },
  ],
  market_events: [
    {
      id: "mkt_black_denim_drop",
      product_id: "prod_black_denim",
      product_name: "Black Denim",
      category: "Denim & Apparel",
      event_type: "price_drop",
      old_value: 4398,
      new_value: 3899,
      change_pct: -11.3,
      affected_shoppers: 23,
      avg_shopper_intent: 0.91,
      avg_drop_off_risk: 0.78,
      summary:
        "Price dropped 11.3% (₹4,398 → ₹3,899) while 23 high-intent shoppers have active cart/watchlist signals.",
      timestamp: new Date(Date.now() - 180000).toISOString(),
    },
    {
      id: "mkt_ceramic_mug_stock",
      product_id: "prod_ceramic_mug",
      product_name: "Ceramic Mug Set",
      category: "Home & Objects",
      event_type: "low_stock",
      old_value: 36,
      new_value: 12,
      change_pct: -66.7,
      affected_shoppers: 41,
      avg_shopper_intent: 0.84,
      avg_drop_off_risk: 0.62,
      summary:
        "Inventory dropped to 12 remaining units with 327 watchlist saves and 41 high-intent active shoppers.",
      timestamp: new Date(Date.now() - 480000).toISOString(),
    },
    {
      id: "mkt_headphones_drop",
      product_id: "prod_studio_headphones",
      product_name: "Studio Monitor Headphones",
      category: "Electronics",
      event_type: "price_drop",
      old_value: 10499,
      new_value: 8999,
      change_pct: -14.3,
      affected_shoppers: 18,
      avg_shopper_intent: 0.87,
      avg_drop_off_risk: 0.74,
      summary:
        "Price reduced by ₹1,500 (-14.3%) across 18 high-intent shoppers comparing audio gear.",
      timestamp: new Date(Date.now() - 840000).toISOString(),
    },
    {
      id: "mkt_sneakers_discount",
      product_id: "prod_sneakers",
      product_name: "Terra Runner Sneakers",
      category: "Sneakers",
      event_type: "new_discount",
      old_value: 12995,
      new_value: 11499,
      change_pct: -11.5,
      affected_shoppers: 19,
      avg_shopper_intent: 0.86,
      avg_drop_off_risk: 0.71,
      summary: "Member flash reduction (-11.5%) unlocked for 19 high-intent sneaker carts.",
      timestamp: new Date(Date.now() - 1260000).toISOString(),
    },
  ],
  actions: [
    {
      id: "act_4821_nudge",
      action_type: "in_app_nudge",
      action_label: "In-app price-drop nudge",
      shopper_id: "shopper_4821",
      shopper_display_id: "#4821",
      product_id: "prod_black_denim",
      product_name: "Black Denim",
      product_price: 3899,
      opportunity_id: "opp_black_denim_price_drop",
      trigger: "Price dropped 11.3%",
      reason: "Shopper #4821 exhibited 91% purchase intent and hesitation loop on Black Denim.",
      message: "Black Denim is now ₹3,899.",
      intent_score: 0.91,
      drop_off_risk: 0.78,
      status: "delivered",
      result: "Checkout resumed",
      revenue_recovered: 3899,
      created_at: new Date(Date.now() - 28000).toISOString(),
    },
    {
      id: "act_4821_webhook",
      action_type: "webhook",
      action_label: "POST /webhooks/recovery",
      shopper_id: "shopper_4821",
      shopper_display_id: "#4821",
      product_id: "prod_black_denim",
      product_name: "Black Denim",
      product_price: 3899,
      opportunity_id: "opp_black_denim_price_drop",
      trigger: "Hesitation loop + 11.3% price reduction",
      reason: "Dispatched real-time storefront overlay payload for Shopper #4821.",
      message: '{"shopper":"#4821","product":"Black Denim","new_price":3899,"intent":0.91}',
      intent_score: 0.91,
      drop_off_risk: 0.78,
      status: "converted",
      result: "200 OK · Storefront banner rendered (34ms)",
      revenue_recovered: 3899,
      created_at: new Date(Date.now() - 26000).toISOString(),
    },
    {
      id: "act_7719_inventory",
      action_type: "in_app_nudge",
      action_label: "Low-inventory urgency nudge",
      shopper_id: "shopper_7719",
      shopper_display_id: "#7719",
      product_id: "prod_ceramic_mug",
      product_name: "Ceramic Mug Set",
      product_price: 2499,
      opportunity_id: "opp_ceramic_mug_inventory",
      trigger: "Inventory dropped to 12 remaining (327 watching)",
      reason: "Shopper #7719 checked stock twice with 84% purchase intent.",
      message: "Only 12 Ceramic Mug Sets remain in this glaze batch.",
      intent_score: 0.84,
      drop_off_risk: 0.62,
      status: "converted",
      result: "Order completed · ₹2,499 recovered",
      revenue_recovered: 2499,
      created_at: new Date(Date.now() - 240000).toISOString(),
    },
    {
      id: "act_2204_headphones",
      action_type: "re_engagement",
      action_label: "High-intent cart re-engagement",
      shopper_id: "shopper_2204",
      shopper_display_id: "#2204",
      product_id: "prod_studio_headphones",
      product_name: "Studio Monitor Headphones",
      product_price: 8999,
      opportunity_id: "opp_headphones_recovery",
      trigger: "Price decreased 14.3% (₹10,499 → ₹8,999)",
      reason: "Shopper #2204 compared 2 audio products and checked price 4 times.",
      message: "Studio Monitor Headphones dropped to ₹8,999 for your active session.",
      intent_score: 0.89,
      drop_off_risk: 0.74,
      status: "clicked",
      result: "Shopper clicked nudge · reviewing payment",
      revenue_recovered: 8999,
      created_at: new Date(Date.now() - 540000).toISOString(),
    },
  ],
  campaigns: [
    {
      id: "camp_price_drop_intent",
      name: "Price Drop × High Purchase Intent",
      trigger_condition: "Product price drops ≥ 8% AND Shopper Intent ≥ 80%",
      target_segment: "High-intent cart & watchlist shoppers",
      action_type: "In-App Nudge + Webhook",
      status: "active",
      enrolled_shoppers: 142,
      actions_sent: 118,
      conversions: 49,
      conversion_rate: 41.5,
      recovered_revenue: 164820,
      last_triggered: new Date(Date.now() - 60000).toISOString(),
    },
    {
      id: "camp_hesitation_loop",
      name: "Hesitation Loop Interception",
      trigger_condition: "≥ 3 Product Views + Cart Add + ≥ 2 Price Checks + Return Session",
      target_segment: "Active session hesitation loops",
      action_type: "Real-Time Storefront Overlay",
      status: "active",
      enrolled_shoppers: 89,
      actions_sent: 84,
      conversions: 33,
      conversion_rate: 39.3,
      recovered_revenue: 112450,
      last_triggered: new Date(Date.now() - 180000).toISOString(),
    },
    {
      id: "camp_inventory_pressure",
      name: "Inventory Scarcity Signal",
      trigger_condition: "Inventory ≤ 15 units AND Watchlist ≥ 100 AND Intent ≥ 75%",
      target_segment: "High-affinity watchlist & repeat viewers",
      action_type: "Scarcity Nudge + Push Alert",
      status: "active",
      enrolled_shoppers: 214,
      actions_sent: 176,
      conversions: 64,
      conversion_rate: 36.4,
      recovered_revenue: 159936,
      last_triggered: new Date(Date.now() - 360000).toISOString(),
    },
    {
      id: "camp_checkout_recovery",
      name: "High-Value Checkout Recovery",
      trigger_condition: "Cart Value ≥ ₹5,000 AND Checkout Abandonment Risk ≥ 65%",
      target_segment: "Stalled high-value checkouts",
      action_type: "Webhook + Concierge Re-engagement",
      status: "active",
      enrolled_shoppers: 63,
      actions_sent: 58,
      conversions: 21,
      conversion_rate: 36.2,
      recovered_revenue: 198400,
      last_triggered: new Date(Date.now() - 720000).toISOString(),
    },
  ],
  webhooks: [
    {
      id: "wh_01",
      endpoint: "POST /webhooks/recovery",
      event_name: "axiom.recovery.nudge_dispatched",
      shopper_display_id: "#4821",
      product_name: "Black Denim",
      status_code: 200,
      latency_ms: 34,
      payload: {
        event: "axiom.recovery.nudge_dispatched",
        shopper_id: "#4821",
        product: "Black Denim",
        old_price: 4398,
        new_price: 3899,
        drop_pct: 11.3,
        purchase_intent: 0.91,
        drop_off_risk: 0.78,
        action: "in_app_nudge",
        message: "Black Denim is now ₹3,899.",
      },
      timestamp: new Date(Date.now() - 26000).toISOString(),
    },
    {
      id: "wh_02",
      endpoint: "POST /webhooks/storefront-overlay",
      event_name: "axiom.intent.hesitation_loop",
      shopper_display_id: "#4821",
      product_name: "Black Denim",
      status_code: 200,
      latency_ms: 29,
      payload: {
        event: "axiom.intent.hesitation_loop",
        shopper_id: "#4821",
        signals: {
          repeated_views: 18,
          added_to_cart: 27,
          price_checks: 21,
          returned_session: 14,
          checkout_hesitation: 11,
        },
        confidence: 0.94,
      },
      timestamp: new Date(Date.now() - 33000).toISOString(),
    },
  ],
};

export async function fetchSnapshot(): Promise<AxiomSnapshot | null> {
  try {
    const res = await fetch(`${API_BASE}/api/snapshot`, { cache: "no-store" });
    if (!res.ok) return null;
    return (await res.json()) as AxiomSnapshot;
  } catch {
    return null;
  }
}

export async function fetchShopperDetail(shopperId: string): Promise<{
  shopper: Shopper;
  events: ShopperEvent[];
  products: Product[];
  opportunities: Opportunity[];
  actions: RecoveryAction[];
} | null> {
  try {
    const res = await fetch(`${API_BASE}/api/shoppers/${encodeURIComponent(shopperId)}`, {
      cache: "no-store",
    });
    if (!res.ok) return null;
    return await res.json();
  } catch {
    return null;
  }
}

export async function activateOpportunityApi(opportunityId: string): Promise<{
  opportunity?: Opportunity;
  actions_triggered?: RecoveryAction[];
} | null> {
  try {
    const res = await fetch(`${API_BASE}/api/opportunities/${encodeURIComponent(opportunityId)}/activate`, {
      method: "POST",
    });
    if (!res.ok) return null;
    return await res.json();
  } catch {
    return null;
  }
}

export async function ingestEventApi(payload: {
  shopper_id: string;
  event_type: string;
  product_id?: string;
  search_query?: string;
}): Promise<{ event: ShopperEvent } | null> {
  try {
    const res = await fetch(`${API_BASE}/api/events/ingest`, {
      method: "POST",
      headers: { "Content-Type": "application/json" },
      body: JSON.stringify(payload),
    });
    if (!res.ok) return null;
    return await res.json();
  } catch {
    return null;
  }
}

export async function simulateMarketEventApi(payload: {
  product_id: string;
  event_type: string;
  new_value?: number;
}): Promise<{
  market_event: MarketEvent;
  opportunities_created: Opportunity[];
  actions_triggered: RecoveryAction[];
} | null> {
  try {
    const res = await fetch(`${API_BASE}/api/market-events/simulate`, {
      method: "POST",
      headers: { "Content-Type": "application/json" },
      body: JSON.stringify(payload),
    });
    if (!res.ok) return null;
    return await res.json();
  } catch {
    return null;
  }
}

export async function toggleCampaignApi(campaignId: string): Promise<Campaign | null> {
  try {
    const res = await fetch(`${API_BASE}/api/campaigns/${encodeURIComponent(campaignId)}/toggle`, {
      method: "POST",
    });
    if (!res.ok) return null;
    return await res.json();
  } catch {
    return null;
  }
}

export async function sendTestWebhookApi(): Promise<WebhookDelivery | null> {
  try {
    const res = await fetch(`${API_BASE}/api/webhooks/test`, {
      method: "POST",
    });
    if (!res.ok) return null;
    return await res.json();
  } catch {
    return null;
  }
}

export function formatINR(amount: number): string {
  return `₹${Math.round(amount).toLocaleString("en-IN")}`;
}

export function formatCompactINR(amount: number): string {
  if (amount >= 100000) {
    return `₹${(amount / 100000).toFixed(2)}L`;
  }
  if (amount >= 1000) {
    return `₹${(amount / 1000).toFixed(1)}K`;
  }
  return `₹${Math.round(amount)}`;
}

export function formatClockTime(iso: string): string {
  try {
    const d = new Date(iso);
    return d.toTimeString().slice(0, 8);
  } catch {
    return "22:41:08";
  }
}
