"""Rich realistic seed dataset for Axiom Autonomous Commerce Intelligence Engine."""
from __future__ import annotations
import random
from datetime import datetime, timedelta
from .models import (
    Product, Shopper, ShopperEvent, EventType, IntentScore,
    MarketEvent, MarketEventType, Opportunity, OpportunityType,
    RecoveryAction, ActionType, ActionStatus, Campaign, WebhookDelivery, gen_id
)
from .store import store

PRODUCTS_DATA = [
    {
        "id": "prod_black_denim",
        "name": "Black Denim",
        "slug": "black-denim-slim-fit",
        "category": "Denim & Apparel",
        "price": 3899,
        "original_price": 4398,
        "competitor_price": 4199,
        "inventory": 38,
        "brand": "Atelier Noir",
        "description": "13.5oz Japanese selvedge black denim with raw matte hardware and tapered silhouette.",
        "views": 1420,
        "cart_adds": 61,
        "wishlist_count": 184,
        "purchases": 89,
        "price_change_pct": -11.3,
        "recovery_opportunity_level": "HIGH",
    },
    {
        "id": "prod_ceramic_mug",
        "name": "Ceramic Mug Set",
        "slug": "ceramic-artisan-mug-set",
        "category": "Home & Objects",
        "price": 2499,
        "original_price": 2499,
        "competitor_price": 2750,
        "inventory": 12,
        "brand": "Kinto Studio",
        "description": "Hand-thrown stoneware mug set of 4 finished in warm ash reactive glaze.",
        "views": 1890,
        "cart_adds": 78,
        "wishlist_count": 327,
        "purchases": 134,
        "price_change_pct": 0.0,
        "recovery_opportunity_level": "HIGH",
    },
    {
        "id": "prod_studio_headphones",
        "name": "Studio Monitor Headphones",
        "slug": "studio-monitor-headphones",
        "category": "Electronics",
        "price": 8999,
        "original_price": 10499,
        "competitor_price": 9499,
        "inventory": 29,
        "brand": "Aether Audio",
        "description": "Planar magnetic wireless studio headphones with adaptive acoustic isolation.",
        "views": 1640,
        "cart_adds": 52,
        "wishlist_count": 264,
        "purchases": 92,
        "price_change_pct": -14.3,
        "recovery_opportunity_level": "HIGH",
    },
    {
        "id": "prod_sneakers",
        "name": "Terra Runner Sneakers",
        "slug": "terra-runner-sneakers",
        "category": "Sneakers",
        "price": 11499,
        "original_price": 12995,
        "competitor_price": 11999,
        "inventory": 21,
        "brand": "Veloce Lab",
        "description": "Carbon-plate everyday trainer in unbleached suede and Vibram micro-lug sole.",
        "views": 2110,
        "cart_adds": 74,
        "wishlist_count": 310,
        "purchases": 118,
        "price_change_pct": -11.5,
        "recovery_opportunity_level": "HIGH",
    },
    {
        "id": "prod_skincare_serum",
        "name": "Cellular Barrier Serum",
        "slug": "cellular-barrier-serum",
        "category": "Skincare",
        "price": 1899,
        "original_price": 2199,
        "competitor_price": 1999,
        "inventory": 94,
        "brand": "Derma Botanica",
        "description": "20% stabilized L-ascorbic acid + ceramide complex for dermal barrier recovery.",
        "views": 1350,
        "cart_adds": 48,
        "wishlist_count": 219,
        "purchases": 112,
        "price_change_pct": -13.6,
        "recovery_opportunity_level": "HIGH",
    },
    {
        "id": "prod_cosmetics_kit",
        "name": "Velvet Matte Lip & Cheek Atelier",
        "slug": "velvet-matte-cosmetics",
        "category": "Cosmetics",
        "price": 1649,
        "original_price": 1899,
        "competitor_price": 1799,
        "inventory": 64,
        "brand": "Maison Lune",
        "description": "Micro-pigment lip and cheek tint trio formulated with botanical squalane.",
        "views": 1180,
        "cart_adds": 44,
        "wishlist_count": 195,
        "purchases": 98,
        "price_change_pct": -13.2,
        "recovery_opportunity_level": "MEDIUM",
    },
    {
        "id": "prod_coffee_table",
        "name": "Nordic White Oak Coffee Table",
        "slug": "nordic-oak-coffee-table",
        "category": "Furniture",
        "price": 18999,
        "original_price": 21999,
        "competitor_price": 19999,
        "inventory": 7,
        "brand": "Forma Living",
        "description": "Solid kiln-dried white oak low table with architectural mortise joinery.",
        "views": 980,
        "cart_adds": 29,
        "wishlist_count": 142,
        "purchases": 41,
        "price_change_pct": -13.6,
        "recovery_opportunity_level": "HIGH",
    },
    {
        "id": "prod_mech_keyboard",
        "name": "Machined Aluminum Field Keyboard",
        "slug": "machined-field-keyboard",
        "category": "Electronics",
        "price": 6499,
        "original_price": 7499,
        "competitor_price": 6899,
        "inventory": 33,
        "brand": "Tactile Works",
        "description": "CNC 6063 aluminum 75% wireless mechanical keyboard with gasket mount.",
        "views": 1240,
        "cart_adds": 39,
        "wishlist_count": 168,
        "purchases": 73,
        "price_change_pct": -13.3,
        "recovery_opportunity_level": "MEDIUM",
    },
    {
        "id": "prod_leather_crossbody",
        "name": "Full-Grain Saddle Crossbody",
        "slug": "saddle-leather-crossbody",
        "category": "Accessories",
        "price": 4299,
        "original_price": 4799,
        "competitor_price": 4599,
        "inventory": 16,
        "brand": "Sienna Craft",
        "description": "Vegetable-tanned Italian bridle leather crossbody with brushed brass clasp.",
        "views": 890,
        "cart_adds": 31,
        "wishlist_count": 128,
        "purchases": 54,
        "price_change_pct": -10.4,
        "recovery_opportunity_level": "MEDIUM",
    },
    {
        "id": "prod_wool_overcoat",
        "name": "Double-Faced Merino Overcoat",
        "slug": "merino-wool-overcoat",
        "category": "Denim & Apparel",
        "price": 9499,
        "original_price": 11499,
        "competitor_price": 10200,
        "inventory": 11,
        "brand": "Atelier Noir",
        "description": "Unlined double-faced Australian merino overcoat in deep charcoal slate.",
        "views": 760,
        "cart_adds": 27,
        "wishlist_count": 154,
        "purchases": 38,
        "price_change_pct": -17.4,
        "recovery_opportunity_level": "HIGH",
    },
    {
        "id": "prod_espresso_grinder",
        "name": "Conical Burr Precision Grinder",
        "slug": "conical-burr-grinder",
        "category": "Home & Objects",
        "price": 7899,
        "original_price": 8499,
        "competitor_price": 8199,
        "inventory": 19,
        "brand": "Kinto Studio",
        "description": "Stepless 48mm titanium-coated burr grinder with low-retention chute.",
        "views": 670,
        "cart_adds": 24,
        "wishlist_count": 116,
        "purchases": 42,
        "price_change_pct": -7.1,
        "recovery_opportunity_level": "MEDIUM",
    },
    {
        "id": "prod_night_repair",
        "name": "Retinol + Peptide Night Emulsion",
        "slug": "retinol-peptide-night-emulsion",
        "category": "Skincare",
        "price": 2199,
        "original_price": 2599,
        "competitor_price": 2399,
        "inventory": 76,
        "brand": "Derma Botanica",
        "description": "Encapsulated 0.5% retinaldehyde with copper tripeptides for overnight renewal.",
        "views": 1040,
        "cart_adds": 41,
        "wishlist_count": 172,
        "purchases": 84,
        "price_change_pct": -15.4,
        "recovery_opportunity_level": "MEDIUM",
    },
]

SEARCH_QUERIES = [
    "black jeans", "selvedge black denim", "ceramic mugs", "artisan mug set",
    "noise cancelling headphones", "studio monitor headphones", "running sneakers",
    "vitamin c barrier serum", "velvet matte lipstick", "solid oak coffee table",
    "wireless mechanical keyboard", "leather crossbody bag", "merino wool coat",
    "burr coffee grinder", "retinol night cream", "minimalist homeware",
]

CITIES = [
    "Mumbai, IN", "Bengaluru, IN", "Delhi NCR, IN", "Hyderabad, IN",
    "Pune, IN", "Chennai, IN", "Kolkata, IN", "Ahmedabad, IN"
]

DEVICES = [
    "iOS · Safari", "macOS · Chrome", "Android · Chrome",
    "macOS · Arc", "Windows · Edge", "iPadOS · Safari"
]

FIRST_NAMES = [
    "Aarav", "Priya", "Rohan", "Ananya", "Vikram", "Meera", "Kabir", "Ishita",
    "Siddharth", "Kavya", "Dev", "Nisha", "Arjun", "Tara", "Aditya", "Riya",
    "Karan", "Sneha", "Nikhil", "Aditi", "Varun", "Simran", "Pranav", "Pooja",
    "Harsh", "Diya", "Kunal", "Shreya", "Manish", "Anjali", "Sahil", "Ritika"
]

LAST_NAMES = [
    "Mehta", "Sharma", "Kapoor", "Nair", "Patel", "Verma", "Reddy", "Iyer",
    "Malhotra", "Joshi", "Singhania", "Bhat", "Desai", "Chopra", "Rao", "Gupta"
]


def seed_all():
    """Populate realistic e-commerce intelligence dataset."""
    if len(store.products) > 0:
        return

    now = datetime.utcnow()

    # 1. Seed Products
    for p_data in PRODUCTS_DATA:
        conv = round((p_data["purchases"] / max(p_data["views"], 1)) * 100, 1)
        history = [
            {"price": p_data["original_price"], "date": (now - timedelta(days=14)).isoformat(), "event": "baseline"},
            {"price": round((p_data["original_price"] + p_data["price"]) / 2), "date": (now - timedelta(days=5)).isoformat(), "event": "adjustment"},
            {"price": p_data["price"], "date": (now - timedelta(minutes=18)).isoformat(), "event": "price_drop" if p_data["price"] < p_data["original_price"] else "stable"},
        ]
        product = Product(
            id=p_data["id"],
            name=p_data["name"],
            slug=p_data["slug"],
            category=p_data["category"],
            price=p_data["price"],
            original_price=p_data["original_price"],
            competitor_price=p_data["competitor_price"],
            inventory=p_data["inventory"],
            brand=p_data["brand"],
            description=p_data["description"],
            views=p_data["views"],
            cart_adds=p_data["cart_adds"],
            wishlist_count=p_data["wishlist_count"],
            purchases=p_data["purchases"],
            conversion_rate=conv,
            price_change_pct=p_data["price_change_pct"],
            recovery_opportunity_level=p_data["recovery_opportunity_level"],
            price_history=history,
        )
        store.add_product(product)

    # 2. Seed Flagship Shoppers
    flagship_shoppers = [
        Shopper(
            id="shopper_4821",
            display_id="#4821",
            name="Aarav Mehta",
            email="aarav.mehta@gmail.com",
            location="Mumbai, IN",
            device="iOS · Safari",
            sessions=4,
            session_duration_sec=845,
            total_events=19,
            cart_items=["prod_black_denim"],
            wishlist_items=["prod_black_denim", "prod_wool_overcoat"],
            purchase_history=["prod_ceramic_mug"],
            primary_product_id="prod_black_denim",
            primary_product_name="Black Denim",
            intent_score=0.91,
            risk_score=0.78,
            confidence=0.94,
            hesitation_loop=True,
            predicted_next_action="High probability of checkout completion within 12m following price-drop nudge (₹4,398 → ₹3,899)",
            signal_breakdown={
                "Repeated product views": 18.0,
                "Added to cart": 27.0,
                "Price checks": 21.0,
                "Returned session": 14.0,
                "Checkout hesitation": 11.0,
            },
            behavioral_features={
                "search_frequency": 3,
                "product_revisit_frequency": 4,
                "session_duration_sec": 845,
                "cart_additions": 2,
                "cart_removals": 0,
                "wishlist_activity": 2,
                "price_check_frequency": 3,
                "checkout_progression": 0.75,
                "return_sessions": 3,
                "product_affinity": 0.94,
                "recency_score": 0.98,
                "historical_conversion_rate": 0.33,
            },
            first_seen=now - timedelta(days=6),
            last_seen=now - timedelta(seconds=24),
            status="active",
        ),
        Shopper(
            id="shopper_3912",
            display_id="#3912",
            name="Priya Sharma",
            email="priya.sharma@outlook.com",
            location="Bengaluru, IN",
            device="macOS · Arc",
            sessions=5,
            session_duration_sec=710,
            total_events=16,
            cart_items=["prod_skincare_serum", "prod_cosmetics_kit"],
            wishlist_items=["prod_skincare_serum", "prod_night_repair"],
            purchase_history=["prod_cosmetics_kit"],
            primary_product_id="prod_skincare_serum",
            primary_product_name="Cellular Barrier Serum",
            intent_score=0.88,
            risk_score=0.69,
            confidence=0.92,
            hesitation_loop=True,
            predicted_next_action="Evaluating bundle threshold — responsive to free express shipping or price-drop alert",
            signal_breakdown={
                "Added to cart": 25.0,
                "Repeated product views": 19.0,
                "Watchlist activity": 16.0,
                "Returned session": 15.0,
                "Price checks": 13.0,
            },
            behavioral_features={
                "search_frequency": 2,
                "product_revisit_frequency": 5,
                "session_duration_sec": 710,
                "cart_additions": 2,
                "cart_removals": 1,
                "wishlist_activity": 3,
                "price_check_frequency": 2,
                "checkout_progression": 0.65,
                "return_sessions": 4,
                "product_affinity": 0.89,
                "recency_score": 0.95,
                "historical_conversion_rate": 0.40,
            },
            first_seen=now - timedelta(days=11),
            last_seen=now - timedelta(seconds=48),
            status="active",
        ),
        Shopper(
            id="shopper_7719",
            display_id="#7719",
            name="Rohan Kapoor",
            email="rohan.kapoor@gmail.com",
            location="Delhi NCR, IN",
            device="macOS · Chrome",
            sessions=3,
            session_duration_sec=620,
            total_events=14,
            cart_items=["prod_ceramic_mug"],
            wishlist_items=["prod_ceramic_mug", "prod_espresso_grinder"],
            purchase_history=[],
            primary_product_id="prod_ceramic_mug",
            primary_product_name="Ceramic Mug Set",
            intent_score=0.84,
            risk_score=0.62,
            confidence=0.89,
            hesitation_loop=False,
            predicted_next_action="High sensitivity to stock depletion (12 units left) — trigger low-inventory urgency nudge",
            signal_breakdown={
                "Added to cart": 24.0,
                "Inventory checks": 18.0,
                "Repeated product views": 17.0,
                "Search specificity": 13.0,
                "Watchlist activity": 12.0,
            },
            behavioral_features={
                "search_frequency": 4,
                "product_revisit_frequency": 3,
                "session_duration_sec": 620,
                "cart_additions": 1,
                "cart_removals": 0,
                "wishlist_activity": 2,
                "price_check_frequency": 2,
                "checkout_progression": 0.50,
                "return_sessions": 2,
                "product_affinity": 0.86,
                "recency_score": 0.92,
                "historical_conversion_rate": 0.25,
            },
            first_seen=now - timedelta(days=4),
            last_seen=now - timedelta(minutes=1, seconds=15),
            status="active",
        ),
        Shopper(
            id="shopper_2204",
            display_id="#2204",
            name="Ananya Nair",
            email="ananya.nair@gmail.com",
            location="Hyderabad, IN",
            device="iOS · Safari",
            sessions=6,
            session_duration_sec=930,
            total_events=22,
            cart_items=["prod_studio_headphones"],
            wishlist_items=["prod_studio_headphones", "prod_mech_keyboard"],
            purchase_history=["prod_mech_keyboard"],
            primary_product_id="prod_studio_headphones",
            primary_product_name="Studio Monitor Headphones",
            intent_score=0.89,
            risk_score=0.74,
            confidence=0.95,
            hesitation_loop=True,
            predicted_next_action="Comparing acoustic specs & checking price history — dispatch 14.3% price-drop webhook",
            signal_breakdown={
                "Added to cart": 26.0,
                "Product comparison": 20.0,
                "Price checks": 19.0,
                "Returned session": 14.0,
                "Checkout hesitation": 10.0,
            },
            behavioral_features={
                "search_frequency": 3,
                "product_revisit_frequency": 6,
                "session_duration_sec": 930,
                "cart_additions": 2,
                "cart_removals": 1,
                "wishlist_activity": 2,
                "price_check_frequency": 4,
                "checkout_progression": 0.80,
                "return_sessions": 5,
                "product_affinity": 0.93,
                "recency_score": 0.96,
                "historical_conversion_rate": 0.50,
            },
            first_seen=now - timedelta(days=9),
            last_seen=now - timedelta(minutes=2),
            status="active",
        ),
        Shopper(
            id="shopper_6140",
            display_id="#6140",
            name="Vikram Singhania",
            email="vikram.s@gmail.com",
            location="Mumbai, IN",
            device="macOS · Safari",
            sessions=4,
            session_duration_sec=780,
            total_events=17,
            cart_items=["prod_sneakers", "prod_black_denim"],
            wishlist_items=["prod_sneakers"],
            purchase_history=["prod_leather_crossbody"],
            primary_product_id="prod_sneakers",
            primary_product_name="Terra Runner Sneakers",
            intent_score=0.86,
            risk_score=0.71,
            confidence=0.91,
            hesitation_loop=True,
            predicted_next_action="High cart value (₹15,398) stalled at shipping step — send instant checkout recovery nudge",
            signal_breakdown={
                "Added to cart": 25.0,
                "Checkout progression": 22.0,
                "Repeated product views": 16.0,
                "Price checks": 13.0,
                "Returned session": 10.0,
            },
            behavioral_features={
                "search_frequency": 2,
                "product_revisit_frequency": 4,
                "session_duration_sec": 780,
                "cart_additions": 2,
                "cart_removals": 0,
                "wishlist_activity": 1,
                "price_check_frequency": 3,
                "checkout_progression": 0.85,
                "return_sessions": 3,
                "product_affinity": 0.88,
                "recency_score": 0.94,
                "historical_conversion_rate": 0.45,
            },
            first_seen=now - timedelta(days=8),
            last_seen=now - timedelta(minutes=3),
            status="active",
        ),
        Shopper(
            id="shopper_8093",
            display_id="#8093",
            name="Meera Iyer",
            email="meera.iyer@gmail.com",
            location="Chennai, IN",
            device="iPadOS · Safari",
            sessions=5,
            session_duration_sec=1120,
            total_events=21,
            cart_items=["prod_coffee_table"],
            wishlist_items=["prod_coffee_table", "prod_ceramic_mug"],
            purchase_history=["prod_ceramic_mug"],
            primary_product_id="prod_coffee_table",
            primary_product_name="Nordic White Oak Coffee Table",
            intent_score=0.82,
            risk_score=0.66,
            confidence=0.90,
            hesitation_loop=False,
            predicted_next_action="High-ticket consideration (₹18,999) + only 7 units in stock — notify of 13.6% price drop",
            signal_breakdown={
                "Time on product page": 23.0,
                "Added to cart": 22.0,
                "Repeated product views": 16.0,
                "Price checks": 12.0,
                "Returned session": 9.0,
            },
            behavioral_features={
                "search_frequency": 2,
                "product_revisit_frequency": 5,
                "session_duration_sec": 1120,
                "cart_additions": 1,
                "cart_removals": 0,
                "wishlist_activity": 2,
                "price_check_frequency": 3,
                "checkout_progression": 0.60,
                "return_sessions": 4,
                "product_affinity": 0.91,
                "recency_score": 0.90,
                "historical_conversion_rate": 0.35,
            },
            first_seen=now - timedelta(days=12),
            last_seen=now - timedelta(minutes=4),
            status="active",
        ),
    ]

    for fs in flagship_shoppers:
        store.add_shopper(fs)
        store.intent_scores[fs.id] = IntentScore(
            shopper_id=fs.id,
            shopper_display_id=fs.display_id,
            purchase_intent=fs.intent_score,
            drop_off_risk=fs.risk_score,
            confidence=fs.confidence,
            hesitation_loop=fs.hesitation_loop,
            predicted_next_action=fs.predicted_next_action,
            signals=fs.signal_breakdown,
            features=fs.behavioral_features,
            top_product_id=fs.primary_product_id,
            top_product_name=fs.primary_product_name,
        )

    # 3. Seed 58 additional realistic shoppers
    product_list = list(store.products.values())
    used_display_ids = {"#4821", "#3912", "#7719", "#2204", "#6140", "#8093"}

    for i in range(58):
        first = FIRST_NAMES[i % len(FIRST_NAMES)]
        last = LAST_NAMES[(i * 3) % len(LAST_NAMES)]
        disp = f"#{random.randint(1100, 9899)}"
        while disp in used_display_ids:
            disp = f"#{random.randint(1100, 9899)}"
        used_display_ids.add(disp)

        primary_prod = product_list[i % len(product_list)]
        secondary_prod = product_list[(i + 3) % len(product_list)]

        # Create realistic distribution of high, medium, and emerging intent shoppers
        if i < 22:
            intent = round(random.uniform(0.71, 0.94), 2)
            risk = round(random.uniform(0.52, 0.84), 2)
            hesitation = random.random() > 0.45
        elif i < 42:
            intent = round(random.uniform(0.45, 0.69), 2)
            risk = round(random.uniform(0.30, 0.62), 2)
            hesitation = False
        else:
            intent = round(random.uniform(0.18, 0.44), 2)
            risk = round(random.uniform(0.15, 0.45), 2)
            hesitation = False

        conf = round(random.uniform(0.76, 0.97), 2)
        cart_ids = [primary_prod.id] if intent >= 0.50 else []
        if intent >= 0.82 and random.random() > 0.5:
            cart_ids.append(secondary_prod.id)

        wish_ids = [primary_prod.id, secondary_prod.id]
        purchased_ids = [product_list[(i + 5) % len(product_list)].id] if random.random() > 0.55 else []

        sig_breakdown = {
            "Repeated product views": round(intent * 22, 1),
            "Added to cart": round(intent * 28, 1) if cart_ids else 0.0,
            "Price checks": round(risk * 24, 1),
            "Returned session": round(intent * 16, 1),
            "Checkout hesitation": round(risk * 14, 1) if hesitation else round(risk * 7, 1),
        }
        sig_breakdown = {k: v for k, v in sig_breakdown.items() if v > 0}

        s = Shopper(
            id=f"shopper_{disp[1:]}",
            display_id=disp,
            name=f"{first} {last}",
            email=f"{first.lower()}.{last.lower()}{i}@gmail.com",
            location=CITIES[i % len(CITIES)],
            device=DEVICES[i % len(DEVICES)],
            sessions=random.randint(2, 9),
            session_duration_sec=random.randint(180, 980),
            total_events=random.randint(8, 34),
            cart_items=cart_ids,
            wishlist_items=wish_ids,
            purchase_history=purchased_ids,
            primary_product_id=primary_prod.id,
            primary_product_name=primary_prod.name,
            intent_score=intent,
            risk_score=risk,
            confidence=conf,
            hesitation_loop=hesitation,
            predicted_next_action=(
                f"Respond to price-drop nudge on {primary_prod.name}"
                if intent >= 0.75
                else f"Monitoring {primary_prod.name} watchlist & comparing options"
            ),
            signal_breakdown=sig_breakdown,
            behavioral_features={
                "search_frequency": random.randint(1, 5),
                "product_revisit_frequency": random.randint(2, 7),
                "session_duration_sec": random.randint(180, 980),
                "cart_additions": len(cart_ids),
                "cart_removals": 1 if hesitation else 0,
                "wishlist_activity": len(wish_ids),
                "price_check_frequency": random.randint(1, 5),
                "checkout_progression": round(intent * 0.85, 2),
                "return_sessions": random.randint(1, 5),
                "product_affinity": round(min(0.98, intent + 0.06), 2),
                "recency_score": round(random.uniform(0.7, 0.99), 2),
                "historical_conversion_rate": round(random.uniform(0.15, 0.55), 2),
            },
            first_seen=now - timedelta(days=random.randint(2, 21)),
            last_seen=now - timedelta(minutes=random.randint(1, 45)),
            status="active",
        )
        store.add_shopper(s)
        store.intent_scores[s.id] = IntentScore(
            shopper_id=s.id,
            shopper_display_id=s.display_id,
            purchase_intent=s.intent_score,
            drop_off_risk=s.risk_score,
            confidence=s.confidence,
            hesitation_loop=s.hesitation_loop,
            predicted_next_action=s.predicted_next_action,
            signals=s.signal_breakdown,
            features=s.behavioral_features,
            top_product_id=primary_prod.id,
            top_product_name=primary_prod.name,
        )

    # 4. Seed Historical + Flagship Story Events (especially #4821's exact narrative!)
    all_shoppers = store.get_all_shoppers()
    for idx in range(120):
        sh = all_shoppers[(idx + 6) % len(all_shoppers)]
        pr = store.get_product(sh.primary_product_id) or product_list[idx % len(product_list)]
        et = [
            EventType.SEARCH, EventType.PRODUCT_VIEW, EventType.ADD_TO_CART,
            EventType.PRICE_CHECK, EventType.WISHLIST_ADD, EventType.RETURN_VISIT,
            EventType.PRODUCT_COMPARE, EventType.CART_ABANDON
        ][idx % 8]
        ts = now - timedelta(minutes=130 - idx, seconds=random.randint(0, 50))
        evt = ShopperEvent(
            shopper_id=sh.id,
            shopper_display_id=sh.display_id,
            event_type=et,
            label=et.value.replace("_", " ").upper(),
            detail=f'{sh.display_id} {et.value.replace("_", " ")} · {pr.name}',
            timestamp=ts,
            product_id=pr.id,
            product_name=pr.name,
            product_price=pr.price,
            search_query=pr.name.lower() if et == EventType.SEARCH else None,
            metadata={"shopper_display_id": sh.display_id, "product_price": pr.price, "product_category": pr.category},
        )
        store.add_event(evt, persist=False)

    # Exact canonical sequence for #4821 so the live stream & shopper detail show the exact story
    story_events = [
        (now - timedelta(minutes=4, seconds=12), "shopper_4821", "#4821", EventType.SEARCH, "SEARCH", '#4821 searched "black jeans"', "prod_black_denim", "Black Denim", 4398, "black jeans", False),
        (now - timedelta(minutes=3, seconds=49), "shopper_4821", "#4821", EventType.PRODUCT_VIEW, "PRODUCT VIEW", "#4821 viewed Black Denim (4× revisit · ₹4,398)", "prod_black_denim", "Black Denim", 4398, None, False),
        (now - timedelta(minutes=3, seconds=16), "shopper_4821", "#4821", EventType.ADD_TO_CART, "ADDED TO CART", "#4821 added Black Denim to cart · ₹4,398", "prod_black_denim", "Black Denim", 4398, None, False),
        (now - timedelta(minutes=2, seconds=1), "shopper_4821", "#4821", EventType.PRICE_CHECK, "PRICE CHECK", "#4821 checked price on Black Denim (3× check)", "prod_black_denim", "Black Denim", 4398, None, False),
        (now - timedelta(minutes=1, seconds=18), "shopper_4821", "#4821", EventType.CART_ABANDON, "LEFT CART", "#4821 left cart without completing checkout", "prod_black_denim", "Black Denim", 4398, None, False),
        (now - timedelta(seconds=38), "shopper_4821", "#4821", EventType.RETURN_VISIT, "RETURNED", "#4821 returned to Black Denim session", "prod_black_denim", "Black Denim", 3899, None, False),
        (now - timedelta(seconds=34), "shopper_4821", "#4821", EventType.HESITATION_DETECTED, "AXIOM DETECTED HESITATION LOOP", "91% Purchase Intent · 78% Drop-Off Risk · Price sensitivity confirmed", "prod_black_denim", "Black Denim", 3899, None, True),
        (now - timedelta(seconds=22), "shopper_3912", "#3912", EventType.PRICE_CHECK, "PRICE CHECK", "#3912 checked price on Cellular Barrier Serum", "prod_skincare_serum", "Cellular Barrier Serum", 1899, None, False),
        (now - timedelta(seconds=14), "shopper_7719", "#7719", EventType.PRODUCT_VIEW, "PRODUCT VIEW", "#7719 checked stock on Ceramic Mug Set (12 left)", "prod_ceramic_mug", "Ceramic Mug Set", 2499, None, False),
        (now - timedelta(seconds=6), "shopper_2204", "#2204", EventType.PRODUCT_COMPARE, "PRODUCT COMPARE", "#2204 compared Studio Monitor Headphones vs Machined Keyboard", "prod_studio_headphones", "Studio Monitor Headphones", 8999, None, False),
    ]
    for ts, sid, sdisp, et, label, detail, pid, pname, pprice, sq, is_ax in story_events:
        store.add_event(
            ShopperEvent(
                shopper_id=sid,
                shopper_display_id=sdisp,
                event_type=et,
                label=label,
                detail=detail,
                timestamp=ts,
                product_id=pid,
                product_name=pname,
                product_price=pprice,
                search_query=sq,
                is_axiom_signal=is_ax,
                metadata={"shopper_display_id": sdisp, "product_price": pprice, "axiom_flag": is_ax},
            )
        )

    # 5. Seed Market Events
    market_seed = [
        MarketEvent(
            id="mkt_black_denim_drop",
            product_id="prod_black_denim",
            product_name="Black Denim",
            category="Denim & Apparel",
            event_type=MarketEventType.PRICE_DROP,
            old_value=4398,
            new_value=3899,
            change_pct=-11.3,
            affected_shoppers=23,
            avg_shopper_intent=0.91,
            avg_drop_off_risk=0.78,
            summary="Price dropped 11.3% (₹4,398 → ₹3,899) while 23 high-intent shoppers have active cart/watchlist signals.",
            timestamp=now - timedelta(minutes=3),
            metadata={"reduction_inr": 499, "trigger_source": "Dynamic Catalog Feed"},
        ),
        MarketEvent(
            id="mkt_ceramic_mug_stock",
            product_id="prod_ceramic_mug",
            product_name="Ceramic Mug Set",
            category="Home & Objects",
            event_type=MarketEventType.LOW_STOCK,
            old_value=36,
            new_value=12,
            change_pct=-66.7,
            affected_shoppers=41,
            avg_shopper_intent=0.84,
            avg_drop_off_risk=0.62,
            summary="Inventory dropped to 12 remaining units with 327 watchlist saves and 41 high-intent active shoppers.",
            timestamp=now - timedelta(minutes=8),
            metadata={"watchlist": 327, "urgency": "HIGH"},
        ),
        MarketEvent(
            id="mkt_headphones_drop",
            product_id="prod_studio_headphones",
            product_name="Studio Monitor Headphones",
            category="Electronics",
            event_type=MarketEventType.PRICE_DROP,
            old_value=10499,
            new_value=8999,
            change_pct=-14.3,
            affected_shoppers=18,
            avg_shopper_intent=0.87,
            avg_drop_off_risk=0.74,
            summary="Price reduced by ₹1,500 (-14.3%) across 18 high-intent shoppers comparing audio gear.",
            timestamp=now - timedelta(minutes=14),
            metadata={"reduction_inr": 1500, "trigger_source": "Competitor Match Rule"},
        ),
        MarketEvent(
            id="mkt_sneakers_discount",
            product_id="prod_sneakers",
            product_name="Terra Runner Sneakers",
            category="Sneakers",
            event_type=MarketEventType.NEW_DISCOUNT,
            old_value=12995,
            new_value=11499,
            change_pct=-11.5,
            affected_shoppers=19,
            avg_shopper_intent=0.86,
            avg_drop_off_risk=0.71,
            summary="Member flash reduction (-11.5%) unlocked for 19 high-intent sneaker carts.",
            timestamp=now - timedelta(minutes=21),
            metadata={"reduction_inr": 1496, "discount_type": "Tier Flash"},
        ),
        MarketEvent(
            id="mkt_table_stock",
            product_id="prod_coffee_table",
            product_name="Nordic White Oak Coffee Table",
            category="Furniture",
            event_type=MarketEventType.LOW_STOCK,
            old_value=18,
            new_value=7,
            change_pct=-61.1,
            affected_shoppers=16,
            avg_shopper_intent=0.82,
            avg_drop_off_risk=0.66,
            summary="Batch inventory down to 7 handcrafted units; 142 shoppers watching.",
            timestamp=now - timedelta(minutes=29),
            metadata={"watchlist": 142, "urgency": "HIGH"},
        ),
        MarketEvent(
            id="mkt_serum_drop",
            product_id="prod_skincare_serum",
            product_name="Cellular Barrier Serum",
            category="Skincare",
            event_type=MarketEventType.PRICE_DROP,
            old_value=2199,
            new_value=1899,
            change_pct=-13.6,
            affected_shoppers=27,
            avg_shopper_intent=0.88,
            avg_drop_off_risk=0.69,
            summary="Price dropped ₹300 (-13.6%) with 27 high-intent replenish & cart-hesitant shoppers.",
            timestamp=now - timedelta(minutes=37),
            metadata={"reduction_inr": 300},
        ),
    ]
    for m in market_seed:
        store.add_market_event(m)

    # 6. Seed Opportunities (including exact prompt examples)
    opportunities_seed = [
        Opportunity(
            id="opp_black_denim_price_drop",
            title="HIGH INTENT + PRICE DROP",
            opportunity_type=OpportunityType.HIGH_INTENT_PRICE_DROP,
            product_id="prod_black_denim",
            product_name="Black Denim",
            product_price=3899,
            old_price=4398,
            price_reduction=499,
            inventory_remaining=38,
            watchlist_count=184,
            shopper_ids=["shopper_4821", "shopper_6140"],
            shopper_count=23,
            avg_intent=0.91,
            avg_risk=0.78,
            revenue_potential=89677,
            trigger="Price dropped 11.3% (₹4,398 → ₹3,899)",
            description="23 shoppers with 91% average intent and repeated price checks have Black Denim in cart or watchlist following a ₹499 price reduction.",
            recommended_action="Notify high-intent abandoned carts",
            action_channel="In-app price-drop nudge + Webhook",
            urgency="HIGH",
            status="active",
            created_at=now - timedelta(minutes=2),
        ),
        Opportunity(
            id="opp_ceramic_mug_inventory",
            title="INVENTORY PRESSURE",
            opportunity_type=OpportunityType.INVENTORY_PRESSURE,
            product_id="prod_ceramic_mug",
            product_name="Ceramic Mug Set",
            product_price=2499,
            old_price=2499,
            price_reduction=0,
            inventory_remaining=12,
            watchlist_count=327,
            shopper_ids=["shopper_7719", "shopper_8093"],
            shopper_count=41,
            avg_intent=0.84,
            avg_risk=0.62,
            revenue_potential=29988,
            trigger="12 units remaining · 327 on watchlist · 41 high-intent",
            description="Potential urgency opportunity: Ceramic Mug Set stock fell to 12 units while 41 high-intent shoppers actively revisit the product page.",
            recommended_action="Dispatch low-stock scarcity signal to 41 high-intent shoppers",
            action_channel="In-app urgency nudge + Push",
            urgency="HIGH",
            status="active",
            created_at=now - timedelta(minutes=6),
        ),
        Opportunity(
            id="opp_4821_hesitation_loop",
            title="HESITATION LOOP INTERCEPTION",
            opportunity_type=OpportunityType.HESITATION_LOOP,
            product_id="prod_black_denim",
            product_name="Black Denim",
            product_price=3899,
            old_price=4398,
            price_reduction=499,
            inventory_remaining=38,
            watchlist_count=184,
            shopper_ids=["shopper_4821"],
            shopper_count=1,
            avg_intent=0.91,
            avg_risk=0.78,
            revenue_potential=3899,
            trigger="4× product views · added to cart · 3× price checks · returned session",
            description="Shopper #4821 returned after abandoning cart and checking price 3 times. Immediate price-drop nudge unlocks checkout.",
            recommended_action="Trigger instant in-app price-drop nudge",
            action_channel="In-app nudge",
            urgency="HIGH",
            status="active",
            created_at=now - timedelta(minutes=1),
        ),
        Opportunity(
            id="opp_headphones_recovery",
            title="HIGH INTENT + PRICE DROP",
            opportunity_type=OpportunityType.HIGH_INTENT_PRICE_DROP,
            product_id="prod_studio_headphones",
            product_name="Studio Monitor Headphones",
            product_price=8999,
            old_price=10499,
            price_reduction=1500,
            inventory_remaining=29,
            watchlist_count=264,
            shopper_ids=["shopper_2204"],
            shopper_count=18,
            avg_intent=0.89,
            avg_risk=0.74,
            revenue_potential=161982,
            trigger="Price dropped 14.3% (₹10,499 → ₹8,999)",
            description="18 high-intent shoppers comparing Studio Monitor Headphones have active carts/watchlists after a ₹1,500 price drop.",
            recommended_action="Activate price-drop recovery campaign",
            action_channel="Webhook + Email Re-engagement",
            urgency="HIGH",
            status="active",
            created_at=now - timedelta(minutes=11),
        ),
        Opportunity(
            id="opp_serum_abandon",
            title="ABANDONED CART + PRICE DROP",
            opportunity_type=OpportunityType.CART_ABANDON_RECOVERY,
            product_id="prod_skincare_serum",
            product_name="Cellular Barrier Serum",
            product_price=1899,
            old_price=2199,
            price_reduction=300,
            inventory_remaining=94,
            watchlist_count=219,
            shopper_ids=["shopper_3912"],
            shopper_count=27,
            avg_intent=0.88,
            avg_risk=0.69,
            revenue_potential=51273,
            trigger="27 high-intent carts + 13.6% price drop",
            description="27 shoppers with 88% average intent stalled at checkout on Cellular Barrier Serum.",
            recommended_action="Send targeted re-engagement nudge",
            action_channel="In-app nudge + Klaviyo Webhook",
            urgency="MEDIUM",
            status="active",
            created_at=now - timedelta(minutes=17),
        ),
        Opportunity(
            id="opp_table_scarcity",
            title="INVENTORY PRESSURE",
            opportunity_type=OpportunityType.INVENTORY_PRESSURE,
            product_id="prod_coffee_table",
            product_name="Nordic White Oak Coffee Table",
            product_price=18999,
            old_price=21999,
            price_reduction=3000,
            inventory_remaining=7,
            watchlist_count=142,
            shopper_ids=["shopper_8093"],
            shopper_count=16,
            avg_intent=0.82,
            avg_risk=0.66,
            revenue_potential=132993,
            trigger="Only 7 units remaining · ₹3,000 price drop",
            description="High-ticket furniture piece has 16 high-intent shoppers and only 7 units left in warehouse.",
            recommended_action="Trigger VIP reservation & low-stock alert",
            action_channel="Concierge Webhook + In-app Banner",
            urgency="HIGH",
            status="active",
            created_at=now - timedelta(minutes=24),
        ),
    ]
    for opp in opportunities_seed:
        store.add_opportunity(opp)

    # 7. Seed Autonomous Actions
    actions_seed = [
        RecoveryAction(
            id="act_4821_nudge",
            action_type=ActionType.IN_APP_NUDGE,
            action_label="In-app price-drop nudge",
            shopper_id="shopper_4821",
            shopper_display_id="#4821",
            product_id="prod_black_denim",
            product_name="Black Denim",
            product_price=3899,
            opportunity_id="opp_black_denim_price_drop",
            trigger="Price dropped 11.3% (₹4,398 → ₹3,899)",
            reason="Shopper #4821 exhibited 91% purchase intent and hesitation loop (4× views, cart add, 3× price checks, return session).",
            message="Black Denim is now ₹3,899.",
            intent_score=0.91,
            drop_off_risk=0.78,
            status=ActionStatus.DELIVERED,
            result="Checkout resumed · ₹3,899 cart active",
            revenue_recovered=3899,
            created_at=now - timedelta(seconds=28),
            delivered_at=now - timedelta(seconds=27),
        ),
        RecoveryAction(
            id="act_4821_webhook",
            action_type=ActionType.WEBHOOK,
            action_label="POST /webhooks/recovery",
            shopper_id="shopper_4821",
            shopper_display_id="#4821",
            product_id="prod_black_denim",
            product_name="Black Denim",
            product_price=3899,
            opportunity_id="opp_black_denim_price_drop",
            trigger="Hesitation loop + 11.3% price reduction",
            reason="Dispatched real-time storefront overlay payload for Shopper #4821.",
            message='{"shopper":"#4821","product":"Black Denim","new_price":3899,"intent":0.91}',
            intent_score=0.91,
            drop_off_risk=0.78,
            status=ActionStatus.CONVERTED,
            result="200 OK · Storefront banner rendered (34ms)",
            revenue_recovered=3899,
            created_at=now - timedelta(seconds=26),
            delivered_at=now - timedelta(seconds=26),
        ),
        RecoveryAction(
            id="act_7719_inventory",
            action_type=ActionType.IN_APP_NUDGE,
            action_label="Low-inventory urgency nudge",
            shopper_id="shopper_7719",
            shopper_display_id="#7719",
            product_id="prod_ceramic_mug",
            product_name="Ceramic Mug Set",
            product_price=2499,
            opportunity_id="opp_ceramic_mug_inventory",
            trigger="Inventory dropped to 12 remaining (327 watching)",
            reason="Shopper #7719 checked stock twice with 84% purchase intent.",
            message="Only 12 Ceramic Mug Sets remain in this glaze batch.",
            intent_score=0.84,
            drop_off_risk=0.62,
            status=ActionStatus.CONVERTED,
            result="Order completed · ₹2,499 recovered",
            revenue_recovered=2499,
            created_at=now - timedelta(minutes=4),
            delivered_at=now - timedelta(minutes=4),
        ),
        RecoveryAction(
            id="act_2204_headphones",
            action_type=ActionType.RE_ENGAGEMENT,
            action_label="High-intent cart re-engagement",
            shopper_id="shopper_2204",
            shopper_display_id="#2204",
            product_id="prod_studio_headphones",
            product_name="Studio Monitor Headphones",
            product_price=8999,
            opportunity_id="opp_headphones_recovery",
            trigger="Price decreased 14.3% (₹10,499 → ₹8,999)",
            reason="Shopper #2204 compared 2 audio products and checked price 4 times.",
            message="Studio Monitor Headphones dropped to ₹8,999 for your active session.",
            intent_score=0.89,
            drop_off_risk=0.74,
            status=ActionStatus.CLICKED,
            result="Shopper clicked nudge · reviewing payment",
            revenue_recovered=8999,
            created_at=now - timedelta(minutes=9),
            delivered_at=now - timedelta(minutes=9),
        ),
        RecoveryAction(
            id="act_3912_serum",
            action_type=ActionType.CAMPAIGN,
            action_label="Price drop + high intent campaign",
            shopper_id="shopper_3912",
            shopper_display_id="#3912",
            product_id="prod_skincare_serum",
            product_name="Cellular Barrier Serum",
            product_price=1899,
            opportunity_id="opp_serum_abandon",
            trigger="Price dropped 13.6% + 88% intent score",
            reason="Shopper #3912 returned for 5th session with active skincare cart.",
            message="Cellular Barrier Serum is now ₹1,899 — reserved in your bag.",
            intent_score=0.88,
            drop_off_risk=0.69,
            status=ActionStatus.CONVERTED,
            result="Checkout completed · ₹1,899 recovered",
            revenue_recovered=1899,
            created_at=now - timedelta(minutes=15),
            delivered_at=now - timedelta(minutes=15),
        ),
        RecoveryAction(
            id="act_6140_sneakers",
            action_type=ActionType.IN_APP_NUDGE,
            action_label="Checkout hesitation recovery",
            shopper_id="shopper_6140",
            shopper_display_id="#6140",
            product_id="prod_sneakers",
            product_name="Terra Runner Sneakers",
            product_price=11499,
            opportunity_id="opp_black_denim_price_drop",
            trigger="Price dropped 11.5% + checkout stall",
            reason="Shopper #6140 paused at shipping step with ₹15,398 cart.",
            message="Terra Runner Sneakers now ₹11,499 with complimentary express dispatch.",
            intent_score=0.86,
            drop_off_risk=0.71,
            status=ActionStatus.CONVERTED,
            result="Order completed · ₹11,499 recovered",
            revenue_recovered=11499,
            created_at=now - timedelta(minutes=22),
            delivered_at=now - timedelta(minutes=22),
        ),
    ]
    for act in actions_seed:
        store.add_action(act)

    # 8. Seed Campaigns
    store.campaigns = [
        Campaign(
            id="camp_price_drop_intent",
            name="Price Drop × High Purchase Intent",
            trigger_condition="Product price drops ≥ 8% AND Shopper Intent ≥ 80%",
            target_segment="High-intent cart & watchlist shoppers",
            action_type="In-App Nudge + Webhook",
            status="active",
            enrolled_shoppers=142,
            actions_sent=118,
            conversions=49,
            conversion_rate=41.5,
            recovered_revenue=164820,
            last_triggered=now - timedelta(minutes=1),
        ),
        Campaign(
            id="camp_hesitation_loop",
            name="Hesitation Loop Interception",
            trigger_condition="≥ 3 Product Views + Cart Add + ≥ 2 Price Checks + Return Session",
            target_segment="Active session hesitation loops",
            action_type="Real-Time Storefront Overlay",
            status="active",
            enrolled_shoppers=89,
            actions_sent=84,
            conversions=33,
            conversion_rate=39.3,
            recovered_revenue=112450,
            last_triggered=now - timedelta(minutes=3),
        ),
        Campaign(
            id="camp_inventory_pressure",
            name="Inventory Scarcity Signal",
            trigger_condition="Inventory ≤ 15 units AND Watchlist ≥ 100 AND Intent ≥ 75%",
            target_segment="High-affinity watchlist & repeat viewers",
            action_type="Scarcity Nudge + Push Alert",
            status="active",
            enrolled_shoppers=214,
            actions_sent=176,
            conversions=64,
            conversion_rate=36.4,
            recovered_revenue=159936,
            last_triggered=now - timedelta(minutes=6),
        ),
        Campaign(
            id="camp_checkout_recovery",
            name="High-Value Checkout Recovery",
            trigger_condition="Cart Value ≥ ₹5,000 AND Checkout Abandonment Risk ≥ 65%",
            target_segment="Stalled high-value checkouts",
            action_type="Webhook + Concierge Re-engagement",
            status="active",
            enrolled_shoppers=63,
            actions_sent=58,
            conversions=21,
            conversion_rate=36.2,
            recovered_revenue=198400,
            last_triggered=now - timedelta(minutes=12),
        ),
    ]

    # 9. Seed Webhooks
    store.webhooks = [
        WebhookDelivery(
            id="wh_01",
            endpoint="POST /webhooks/recovery",
            event_name="axiom.recovery.nudge_dispatched",
            shopper_display_id="#4821",
            product_name="Black Denim",
            status_code=200,
            latency_ms=34,
            payload={
                "event": "axiom.recovery.nudge_dispatched",
                "shopper_id": "#4821",
                "product": "Black Denim",
                "old_price": 4398,
                "new_price": 3899,
                "drop_pct": 11.3,
                "purchase_intent": 0.91,
                "drop_off_risk": 0.78,
                "action": "in_app_nudge",
                "message": "Black Denim is now ₹3,899.",
            },
            timestamp=now - timedelta(seconds=26),
        ),
        WebhookDelivery(
            id="wh_02",
            endpoint="POST /webhooks/storefront-overlay",
            event_name="axiom.intent.hesitation_loop",
            shopper_display_id="#4821",
            product_name="Black Denim",
            status_code=200,
            latency_ms=29,
            payload={
                "event": "axiom.intent.hesitation_loop",
                "shopper_id": "#4821",
                "signals": {"repeated_views": 18, "added_to_cart": 27, "price_checks": 21, "returned_session": 14, "checkout_hesitation": 11},
                "confidence": 0.94,
            },
            timestamp=now - timedelta(seconds=33),
        ),
        WebhookDelivery(
            id="wh_03",
            endpoint="POST /webhooks/recovery",
            event_name="axiom.opportunity.inventory_pressure",
            shopper_display_id="#7719",
            product_name="Ceramic Mug Set",
            status_code=200,
            latency_ms=41,
            payload={
                "event": "axiom.opportunity.inventory_pressure",
                "shopper_id": "#7719",
                "product": "Ceramic Mug Set",
                "inventory_remaining": 12,
                "watchlist_count": 327,
                "purchase_intent": 0.84,
            },
            timestamp=now - timedelta(minutes=4),
        ),
        WebhookDelivery(
            id="wh_04",
            endpoint="POST /webhooks/klaviyo-sync",
            event_name="axiom.recovery.re_engagement",
            shopper_display_id="#2204",
            product_name="Studio Monitor Headphones",
            status_code=200,
            latency_ms=52,
            payload={
                "event": "axiom.recovery.re_engagement",
                "shopper_id": "#2204",
                "product": "Studio Monitor Headphones",
                "price": 8999,
                "intent_score": 0.89,
            },
            timestamp=now - timedelta(minutes=9),
        ),
    ]

    store.update_stats()
